### ISSUE TITLE
[Bug]:  No message after dying in plains

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#216] opened 2022-12-27 03:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Contact Details

Van Gogh

### What happened?

A bug happened! no message after I died. 
![image](https://user-images.githubusercontent.com/118859254/209606794-92cb2725-7a09-4642-93c2-c428e2e8d404.png)

Perhaps because i was able to use a resurrection elixir? 

### What browsers are you seeing the problem on?

Firefox

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by sam-thewise** [comment] 2022-12-27 03:53
Duplicate of https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/136

**Closed by sam-thewise** 2022-12-27 03:53 UTC
Labels: bug
