### ISSUE TITLE
[Bug]: "Flee from battle" selectable while looking at consumables 

### ISSUE THREAD

**Issue by SlayerVan** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#217] opened 2022-12-27 03:40 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Contact Details

Van Gogh

### What happened?

A bug happened! if you go slightly down right from a potion you can click flee from battle. not sure if it will even try to flee but something does happen if you click. 

the screen shot doesnt show cursor, but it is just bottom right of the third (clockwise) potion. 
![image](https://user-images.githubusercontent.com/118859254/209607404-22d03ecc-8697-4e12-aed6-d0fa6fe63ba6.png)

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by SlayerVan** [comment] 2022-12-27 03:42
So i used a consumable, and then it popped up i successfully flee, not sur eif its because of first click, or because of where the potion is located, so maybe it thinks im wanting to flee when i clicked on master potion. 

![image](https://user-images.githubusercontent.com/118859254/209607577-c73062fe-9abc-4742-ac95-cf9d05829bb2.png)

**Comment by sam-thewise** [comment] 2022-12-27 03:54
Duplicate of https://github.com/Dragon-Crypto-Gaming/DCG-Bug-Reporter/issues/151

**Closed by sam-thewise** 2022-12-27 03:54 UTC
Labels: bug
