### ISSUE TITLE
[Enhancement]: Quest reward, hover-tooltip request.

### ISSUE THREAD

**Issue by akita066** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#309] opened 2023-01-09 23:49 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

Akita066#5730

### What happened?

It would be really nice to have atleast a simple tooltip to see what these give.
![image](https://user-images.githubusercontent.com/121979441/211430664-73b31db3-6a2f-408b-a335-e20fab032e1a.png)

for example, xp reward, random item reward. (less or more spesific, its good to have a tooltip <3 )

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment] 2023-01-09 23:50
Duplicate of #65

**Closed by Polypup** 2023-01-09 23:50 UTC
Labels: bug
