### ISSUE TITLE
[Bug]: Cant use Legendary healing potion while in battle

### ISSUE THREAD

**Issue by ghostfaceavax** [Dragon-Crypto-Gaming/DCG-Bug-Reporter#298] opened 2023-01-08 00:45 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Contact Details

GhostFace#7161

### What happened?

During battle i should be able to use legendary healing potion to fully heal, however when i click to use potion i get a message returned "you are not dead" and am forced to use a less effective potion.

### What browsers are you seeing the problem on?

All

### Terms and conditions

- [X] I agree to follow DCG's [terms and conditions](https://dragoncrypto.io/terms-of-use)

**Comment by Polypup** [comment] 2023-01-08 01:56
<img width="153" alt="Screenshot 2023-01-07 at 8 56 17 PM" src="https://user-images.githubusercontent.com/85349906/211177268-2855ad53-5bed-4179-a298-b5d7460a5d06.png">

Can you confirm that it's this potion that you cannot use? I'm having no issues using this. Can you try again?

**Comment by ghostfaceavax** [comment] 2023-01-08 02:19
![Screenshot (128)](https://user-images.githubusercontent.com/122186497/211177756-22479453-44ea-43c1-81fc-9736d49c1ba9.png)

**Comment by ghostfaceavax** [comment] 2023-01-08 02:20
![Screenshot (129)](https://user-images.githubusercontent.com/122186497/211177760-ff91441d-1b86-4726-af5b-b6928b687a3f.png)

**Comment by ghostfaceavax** [comment] 2023-01-08 02:20
Yes Legendary Healing potion gives me the message

**Comment by Polypup** [comment] 2023-01-08 06:58
Just curious are you using number keys to select the healing item? The only time this message would occur is if the the item being selected is a resurrection item. 

I've tried on a few characters and cannot replicate.

**Comment by ghostfaceavax** [comment] 2023-01-08 12:59
so when i hover over with mouse it shows name as legendary healing potion which is set under number 8, when i click i get the message you are not dead. however when i click 8 key on keyboard iam able to use legendary healing potion. i think number 8 and 9 are over lapping on my screen.

**Comment by Polypup** [comment] 2023-01-08 17:18
Wow, that's very strange. Can you show a picture of your hotbar? It should look like this: 

<img width="557" alt="Screenshot 2023-01-08 at 12 17 56 PM" src="https://user-images.githubusercontent.com/85349906/211209779-040c325c-7c61-4c7d-ba51-1970a0016c76.png">

**Comment by ghostfaceavax** [comment] 2023-01-08 19:06
![Screenshot (135)](https://user-images.githubusercontent.com/122186497/211214176-aede7acc-3ce6-47f4-b4ab-8d482a401b77.png)

**Comment by neothon** [comment] 2023-01-09 20:42
hmm, I tried reproducing this a lot but couldn't. Can you try again @ghostfaceavax and if possible, may be record a quick video. That would be awesome 🙏

**Comment by ghostfaceavax** [comment] 2023-01-11 01:18
something changed

**Comment by ghostfaceavax** [comment] 2023-01-11 01:19
i no longer get the meessage

**Comment by ghostfaceavax** [comment] 2023-01-11 01:19
i used amnesia potion and changed my stats

**Comment by Polypup** [comment] 2023-01-11 01:34
> 

Yes, this intended.

**Comment by Polypup** [comment] 2023-01-11 01:35
> i no longer get the meessage

The issue should be resolved with the sorting of the consumables

**Closed by Polypup** 2023-01-11 01:35 UTC
Labels: bug
